version: "3.7"

services:
  # backend:
  #   build:
  #     context: ./backend
  #     target: base
  #   ports:
  #     - "3001:3001"
  #   volumes:
  #     - ./backend:/backend
  #     - /backend/node_modules
  #   command: sh -c "npm start"

  frontend:
    build:
      context: ./frontend
      target: base
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    command: sh -c "ng serve --host 0.0.0.0"